# ***************************************************************************
# MAKEFILE.MSVC
#
# Build Hercules for Win32 using MSVC and nmake (static link version)
#
#  SPDX-FileCopyrightText: Copyright Roger Bowler
#  SPDX-License-Identifier: QPL-1.0
# ***************************************************************************
!include makefile-dllmod.msvc
